import logging

PHOTO: dict[str, str] = {
    'st_0': 'QQQQQQQQQQQQQQ',
    'st_1': 'QQQQQQQQQQQQQQ',
    'st_2': 'QQQQQQQQQQQQQQ',
    'st_3': 'QQQQQQQQQQQQQQ',
    'st_4': 'QQQQQQQQQQQQQQ',
    'st_5': 'AgACAgIAAxkBAAIqhmcSbFXzkASZqxtflJSerQUOxbvFAAKi4TEbKKu4S_4rXXJudgg1AQADAgADeQADNgQ',
    'st_6': 'QQQQQQQQQQQQQQ',



    'N1': 'AgACAgIAAxkBAAIqi2cScEy9h-VJ4MnnC_WyMdmGVJyNAAKg4TEbKKu4S1I7fx4HVROlAQADAgADeAADNgQ',
    'N2': 'AgACAgIAAxkBAAIxh2eqTEhD4bI3k8BxI9wwMfL6JzpVAAK0-zEbd2NQSZc_3xX_O-wBAQADAgADeAADNgQ',
    'N3': 'AgACAgIAAxkBAAIxiGeqTJpKu_xjixqpRHTrhl2aMnJSAALZ8TEbFWZRSQo2yu7ygG8sAQADAgADeAADNgQ',
    'N4': 'AgACAgIAAxkBAAIqh2cSb3er8yMX_dZwfu1rA1Zy15IPAAKh4TEbKKu4Swfdg9AQjsNNAQADAgADeAADNgQ',

    'N5': 'AgACAgIAAxkBAAIqhmcSbFXzkASZqxtflJSerQUOxbvFAAKi4TEbKKu4S_4rXXJudgg1AQADAgADeQADNgQ',
    'landing_place': 'AgACAgIAAxkBAAIqhmcSbFXzkASZqxtflJSerQUOxbvFAAKi4TEbKKu4S_4rXXJudgg1AQADAgADeQADNgQ',

    'N6': 'AgACAgIAAxkBAAIxi2eqTQFZS4E2Rvil0ssrdNV-13StAALd8TEbFWZRSXgvwmKmL5_mAQADAgADeAADNgQ',
    'helmet_kosmonavt': 'AgACAgIAAxkBAAIxi2eqTQFZS4E2Rvil0ssrdNV-13StAALd8TEbFWZRSXgvwmKmL5_mAQADAgADeAADNgQ',

    'N7': 'AgACAgIAAxkBAAIxjGeqTSiQat4ruYMaqGBCxotkVxoeAALe8TEbFWZRSYCxHSfU9U4tAQADAgADeAADNgQ',
    'helmet_wanderer': 'AgACAgIAAxkBAAIxjGeqTSiQat4ruYMaqGBCxotkVxoeAALe8TEbFWZRSYCxHSfU9U4tAQADAgADeAADNgQ',

    'N8': 'AgACAgIAAxkBAAIxjWeqTXEZyxJi_InDvI8pued1CJuhAALg8TEbFWZRSQYh5UzRchaNAQADAgADeAADNgQ',
    'helmet_reinforced': 'AgACAgIAAxkBAAIxjWeqTXEZyxJi_InDvI8pued1CJuhAALg8TEbFWZRSQYh5UzRchaNAQADAgADeAADNgQ',
    'helmet': 'AgACAgIAAxkBAAIxjWeqTXEZyxJi_InDvI8pued1CJuhAALg8TEbFWZRSQYh5UzRchaNAQADAgADeAADNgQ',

    'N9': 'AgACAgIAAxkBAAIxjmeqTaNV91krtylDKMhCGJWIPR2nAALh8TEbFWZRSRqgZG3c_A_BAQADAgADeAADNgQ',
    'dress_kosmonavt': 'AgACAgIAAxkBAAIxjmeqTaNV91krtylDKMhCGJWIPR2nAALh8TEbFWZRSRqgZG3c_A_BAQADAgADeAADNgQ',
    'dress_wanderer': 'AgACAgIAAxkBAAIxjmeqTaNV91krtylDKMhCGJWIPR2nAALh8TEbFWZRSRqgZG3c_A_BAQADAgADeAADNgQ',
    'dress_reinforced': 'AgACAgIAAxkBAAIxjmeqTaNV91krtylDKMhCGJWIPR2nAALh8TEbFWZRSRqgZG3c_A_BAQADAgADeAADNgQ',
    'dress': 'AgACAgIAAxkBAAIxjmeqTaNV91krtylDKMhCGJWIPR2nAALh8TEbFWZRSRqgZG3c_A_BAQADAgADeAADNgQ',

    'N10': 'AgACAgIAAxkBAAIxj2eqTdyT_-1eMJVBzLElSOlY8OByAALk8TEbFWZRSVfns-9yUa1gAQADAgADeAADNgQ',
    # Пояс туземца

    'N11': 'AgACAgIAAxkBAAIxkGeqTfCf1Z3fKTYhiz0rwIhJ1GM9AALm8TEbFWZRSWWoGBsAAcrLPQEAAwIAA3gAAzYE',
    # Пестрый пояс туземца

    'N12': 'AgACAgIAAxkBAAIxkWeqTg88SIBNS6V5TUxRo7CvGndRAALo8TEbFWZRSQZD96KMS4TGAQADAgADeAADNgQ',
    'shoes_kosmonavt': 'AgACAgIAAxkBAAIxkWeqTg88SIBNS6V5TUxRo7CvGndRAALo8TEbFWZRSQZD96KMS4TGAQADAgADeAADNgQ',
    'shoes_wanderer': 'AgACAgIAAxkBAAIxkWeqTg88SIBNS6V5TUxRo7CvGndRAALo8TEbFWZRSQZD96KMS4TGAQADAgADeAADNgQ',
    'shoes_reinforced': 'AgACAgIAAxkBAAIxkWeqTg88SIBNS6V5TUxRo7CvGndRAALo8TEbFWZRSQZD96KMS4TGAQADAgADeAADNgQ',
    'shoes': 'AgACAgIAAxkBAAIxkWeqTg88SIBNS6V5TUxRo7CvGndRAALo8TEbFWZRSQZD96KMS4TGAQADAgADeAADNgQ',

    'N13': 'AgACAgIAAxkBAAIxkmeqTmO2C8IbKaFVPvM7oEvRLQQ9AALr8TEbFWZRSUnnFGKt5XLFAQADAgADeAADNgQ',
    # Шляпки из палки и травы

    'N14': 'AgACAgIAAxkBAAIxk2eqTnyaRKg2LrrtCWo_AAGYJf1VcQAC7fExGxVmUUlhHp3OPDCM_wEAAwIAA3gAAzYE',
    # Лапти из травы

    'N15': 'AgACAgIAAxkBAAIxlGeqTpj7EzVwWr18QnvgTPZDsGIoAALu8TEbFWZRSe4kh8GiQcrAAQADAgADeAADNgQ',
    'backpack_foliage': 'AgACAgIAAxkBAAIxlGeqTpj7EzVwWr18QnvgTPZDsGIoAALu8TEbFWZRSe4kh8GiQcrAAQADAgADeAADNgQ',

    'N16': 'AgACAgIAAxkBAAIxlWeqTrh_jXcEpf_B1XdT-9Ke4JJYAALw8TEbFWZRSVj1gVLGEvZRAQADAgADeAADNgQ',
    'backpack_leana': 'AgACAgIAAxkBAAIxlWeqTrh_jXcEpf_B1XdT-9Ke4JJYAALw8TEbFWZRSVj1gVLGEvZRAQADAgADeAADNgQ',

    'N17': 'AgACAgIAAxkBAAIxlmeqTtu7FotczQoeX5OTmmAVIC8oAALx8TEbFWZRSTWTtLQlm1arAQADAgADeAADNgQ',
    # красный крест

    'N18': 'AgACAgIAAxkBAAIxl2eqTvT4Q9cLS6gIUMQmLPZg60UGAALy8TEbFWZRSdzmNazYGJsiAQADAgADeAADNgQ',
    # Бункер

    'N19': 'AgACAgIAAxkBAAIxmGeqTwpKC6teB0U4rYEIWkP-u6pEAAL08TEbFWZRSRUwcb1mKh78AQADAgADeAADNgQ',
    #  Ящик с хламом

    'N20': 'AgACAgIAAxkBAAIxmWeqTyAVmx--aQRLklBZRpyxyfefAAL18TEbFWZRSWSOwRZ2JLSgAQADAgADeAADNgQ',
    'location_meadows': 'AgACAgIAAxkBAAIxmWeqTyAVmx--aQRLklBZRpyxyfefAAL18TEbFWZRSWSOwRZ2JLSgAQADAgADeAADNgQ',
    # Безкрайние луга

    'N21': 'AgACAgIAAxkBAAIxmmeqTzyqPANM61sFH8eQ2QQq0IvUAAL28TEbFWZRSXwnoBI917Z9AQADAgADeAADNgQ',
    # Тропинка в траве

    'N22': 'AgACAgIAAxkBAAIxm2eqT1Ynm6GuRx5mAdZbV4wOpI2JAAL38TEbFWZRSQ34Tkzsuvn6AQADAgADeAADNgQ',
    'G17': 'AgACAgIAAxkBAAIxm2eqT1Ynm6GuRx5mAdZbV4wOpI2JAAL38TEbFWZRSQ34Tkzsuvn6AQADAgADeAADNgQ',

    'N23': 'AgACAgIAAxkBAAIwgWebbMV7psLdGHX4aYYC1RBLlx2jAAKE7zEbjJvYSO-U6cC4ni-zAQADAgADeAADNgQ',
    'spear': 'AgACAgIAAxkBAAIwgWebbMV7psLdGHX4aYYC1RBLlx2jAAKE7zEbjJvYSO-U6cC4ni-zAQADAgADeAADNgQ',

    'N24': 'AgACAgIAAxkBAAIvuWeQ4BJH2kIXMtpdoxjBMFVUEKJBAAIT6zEb7_SISBccRovUVEV8AQADAgADeQADNgQ',
    'wardrobe': 'AgACAgIAAxkBAAIvuWeQ4BJH2kIXMtpdoxjBMFVUEKJBAAIT6zEb7_SISBccRovUVEV8AQADAgADeQADNgQ',

    'N25': 'AgACAgIAAxkBAAIvumeQ4Fr1hfQzdiky8E395HcRoZnEAAIU6zEb7_SISJ3pg7j7GdrkAQADAgADeQADNgQ',
    'f_aid': 'AgACAgIAAxkBAAIvumeQ4Fr1hfQzdiky8E395HcRoZnEAAIU6zEb7_SISJ3pg7j7GdrkAQADAgADeQADNgQ',
    'f_aid_s': 'AgACAgIAAxkBAAIvumeQ4Fr1hfQzdiky8E395HcRoZnEAAIU6zEb7_SISJ3pg7j7GdrkAQADAgADeQADNgQ',

    'N26': 'AgACAgIAAxkBAAIxnGeqT4ZjRq_2bNSos2b_HLps8RKLAAL58TEbFWZRSXkc2htT6BbhAQADAgADeAADNgQ',
    'bandages_s': 'AgACAgIAAxkBAAIxnGeqT4ZjRq_2bNSos2b_HLps8RKLAAL58TEbFWZRSXkc2htT6BbhAQADAgADeAADNgQ',
    'bandages': 'AgACAgIAAxkBAAIxnGeqT4ZjRq_2bNSos2b_HLps8RKLAAL58TEbFWZRSXkc2htT6BbhAQADAgADeAADNgQ',

    'N27': 'AgACAgIAAxkBAAIxnWeqT7B-M9BIR6clOK2Mx8E5Qe41AAL68TEbFWZRSVJiFAk14CKAAQADAgADeAADNgQ',
    'canned_meat': 'AgACAgIAAxkBAAIxnWeqT7B-M9BIR6clOK2Mx8E5Qe41AAL68TEbFWZRSVJiFAk14CKAAQADAgADeAADNgQ',

    'N28': 'AgACAgIAAxkBAAIxnmeqT8qO-gFHOyx_JHsj2pecKDxZAAL78TEbFWZRSe1CzW6lnOmqAQADAgADeAADNgQ',
    'fried_meat': 'AgACAgIAAxkBAAIxnmeqT8qO-gFHOyx_JHsj2pecKDxZAAL78TEbFWZRSe1CzW6lnOmqAQADAgADeAADNgQ',

    'N29': 'AgACAgIAAxkBAAIxn2eqT-MUPlwff7dRSE6EsRLn02PiAAL88TEbFWZRSbtqiskEDq3gAQADAgADeAADNgQ',
    'fried_veins': 'AgACAgIAAxkBAAIxn2eqT-MUPlwff7dRSE6EsRLn02PiAAL88TEbFWZRSbtqiskEDq3gAQADAgADeAADNgQ',

    'N30': 'AgACAgIAAxkBAAIqjmcScW6Rb10nd5I5Wsona3p5AszjAAJT4jEbHaWZSAe-PFtL90t3AQADAgADeAADNgQ',
    'berries': 'AgACAgIAAxkBAAIqjmcScW6Rb10nd5I5Wsona3p5AszjAAJT4jEbHaWZSAe-PFtL90t3AQADAgADeAADNgQ',

    'N31': 'AgACAgIAAxkBAAIxoGeqUDsboNGFYaeP17garVmOVX57AALh7jEbRL5YSZtMa9p72YyHAQADAgADeAADNgQ',
    'bones': 'AgACAgIAAxkBAAIxoGeqUDsboNGFYaeP17garVmOVX57AALh7jEbRL5YSZtMa9p72YyHAQADAgADeAADNgQ',

    'N32': 'AgACAgIAAxkBAAIx2merJLUsh1TY9udX1WqjgSDm9LJRAAKA7TEbWqlYSS4jnciHIyhzAQADAgADeAADNgQ',
    'veins': 'AgACAgIAAxkBAAIx2merJLUsh1TY9udX1WqjgSDm9LJRAAKA7TEbWqlYSS4jnciHIyhzAQADAgADeAADNgQ',

    'N33': 'AgACAgIAAxkBAAIxomeqUFjuzUHIhT130hWfZC9nf7y2AAL_8TEbFWZRSQ4Ya_bwYsfyAQADAgADeAADNgQ',
    'vine_leaves': 'AgACAgIAAxkBAAIxomeqUFjuzUHIhT130hWfZC9nf7y2AAL_8TEbFWZRSQ4Ya_bwYsfyAQADAgADeAADNgQ',

    'N34': 'AgACAgIAAxkBAAIxo2eqUGi-pC4B8JbG2YQ1Kx8LqxTmAAPyMRsVZlFJG6BS9XNk3W8BAAMCAAN4AAM2BA',
    'yel_fl': 'AgACAgIAAxkBAAIxo2eqUGi-pC4B8JbG2YQ1Kx8LqxTmAAPyMRsVZlFJG6BS9XNk3W8BAAMCAAN4AAM2BA',

    'N35': 'AgACAgIAAxkBAAIxpGeqUHbd3zyhDy_uOvT3p1B7EbKAAAIB8jEbFWZRSZUgG3EM2tc5AQADAgADeAADNgQ',
    'stick': 'AgACAgIAAxkBAAIxpGeqUHbd3zyhDy_uOvT3p1B7EbKAAAIB8jEbFWZRSZUgG3EM2tc5AQADAgADeAADNgQ',

    'N36': 'AgACAgIAAxkBAAIxpWeqUINfH2MW20KM7BFhpqmUQDxCAAIC8jEbFWZRSYXbA7eW5_ZkAQADAgADeAADNgQ',
    'raw_meat': 'AgACAgIAAxkBAAIxpWeqUINfH2MW20KM7BFhpqmUQDxCAAIC8jEbFWZRSYXbA7eW5_ZkAQADAgADeAADNgQ',

    'N37': 'AgACAgIAAxkBAAIqj2cSchKVFMB4gUr349VukzxSdphtAAJW4jEbHaWZSKEpshMws2S4AQADAgADeQADNgQ',
    'seed_zlg': 'AgACAgIAAxkBAAIqj2cSchKVFMB4gUr349VukzxSdphtAAJW4jEbHaWZSKEpshMws2S4AQADAgADeQADNgQ',

    'N38': 'AgACAgIAAxkBAAIvuGeQ3aRKnKyrAAFf6gc4GRHQxTKrEwAC_-oxG-_0iEiiLj39fiy8hwEAAwIAA3kAAzYE',
    'backpack': 'AgACAgIAAxkBAAIvuGeQ3aRKnKyrAAFf6gc4GRHQxTKrEwAC_-oxG-_0iEiiLj39fiy8hwEAAwIAA3kAAzYE',
    # Рюкзак

    'N39': 'AgACAgIAAxkBAAIxpmeqUJTvQfXi-P2ofSQpXMYgy-PvAALk7jEbRL5YSZJyopFpLX6iAQADAgADeAADNgQ',
    # Оружейная

    'N40': 'AgACAgIAAxkBAAIxp2eqUKDRA61gTgrMu0RQVrT7r5vuAAID8jEbFWZRSbdURBbirszZAQADAgADeAADNgQ',
    # Лаборатория

    'N41': 'AgACAgIAAxkBAAIxqGeqUKzXHGTzsla3bwsh_5f3VbC_AAIF8jEbFWZRSabJqfvp7t3NAQADAgADeAADNgQ',
    'bio': 'AgACAgIAAxkBAAIxqGeqUKzXHGTzsla3bwsh_5f3VbC_AAIF8jEbFWZRSabJqfvp7t3NAQADAgADeAADNgQ',

    'N42': 'AgACAgIAAxkBAAIxqWeqULnK5O0DcqOl15-OgDx8M25dAAIG8jEbFWZRSQZvXh6Z9JY1AQADAgADeAADNgQ',
    # Карта

    'N43': 'AgACAgIAAxkBAAIxqmeqUN2P7k8y2rO_rmqSWtjORTYYAAIH8jEbFWZRScB1b0RW5R65AQADAgADeAADNgQ',
    'nothink': 'AgACAgIAAxkBAAIxqmeqUN2P7k8y2rO_rmqSWtjORTYYAAIH8jEbFWZRScB1b0RW5R65AQADAgADeAADNgQ',

    'N44': 'AgACAgIAAxkBAAIqiWcSb9-L9nzsnfkMLlkGA9koD_D2AAKQ4TEbKKu4S_va_xJO144AAQEAAwIAA3kAAzYE',
    'luvron_polevoy': 'AgACAgIAAxkBAAIqiWcSb9-L9nzsnfkMLlkGA9koD_D2AAKQ4TEbKKu4S_va_xJO144AAQEAAwIAA3kAAzYE',

    'N45': 'AgACAgIAAxkBAAIxq2eqURIYgXHOMxTQuKpg-Rzjl12lAAIK8jEbFWZRSfFoIpXlm0AyAQADAgADeAADNgQ',
    'blue_rabbit': 'AgACAgIAAxkBAAIxq2eqURIYgXHOMxTQuKpg-Rzjl12lAAIK8jEbFWZRSfFoIpXlm0AyAQADAgADeAADNgQ',

    'N46': 'AgACAgIAAxkBAAIqimcScB8y-2fmjIyuRFaWpg1YtOfFAAKW4TEbKKu4SwMNaONuXMsWAQADAgADeQADNgQ',
    'daron': 'AgACAgIAAxkBAAIqimcScB8y-2fmjIyuRFaWpg1YtOfFAAKW4TEbKKu4SwMNaONuXMsWAQADAgADeQADNgQ',

    'N47': 'QQQQQQQQQQQQQQ',
    'N48': 'QQQQQQQQQQQQQQ',
    'N49': 'QQQQQQQQQQQQQQ',
    'N50': 'AgACAgIAAxkBAAIxq2eqURIYgXHOMxTQuKpg-Rzjl12lAAIK8jEbFWZRSfFoIpXlm0AyAQADAgADeAADNgQ',



}
